### ISSUE TITLE
Feature request: Zoom on mouse wheel 

### ISSUE THREAD

**Issue by SuperPat45** [henrygd/bigpicture#38]
Ability to Zoom images on mouse wheel like google drive

**Comment by ucin3d** [comment]
Any update on mobile zooming?

**Comment by henrygd** [comment]
You should be able to pinch zoom the page (including image) on mobile.

For better pinch zoom, as well as wheel zoom, please see the lightbox library I made this year:

Demo: https://biggerpicture.henrygd.me/

Repo: https://github.com/henrygd/bigger-picture

I'm going to close this issue as I don't forsee this being added to bigpicture. Handling zoom / panning adds a good amount of weight, and one of the only reasons to use this instead of bigger-picture is the slightly smaller size.

**Comment by ucin3d** [comment]
Thanks for the link  to biggerpicture. It provides the solution we were looking for!
