### ISSUE TITLE
Feature request: optional params Youtube

### ISSUE THREAD

**Issue by KumaVolt** [henrygd/bigpicture#39]
Ability to add/remove params for example enablejsapi

https://developers.google.com/youtube/player_parameters#Parameters

**Comment by henrygd** [comment]
Hi Miquel, you can do this by using the `iframeSrc` option instead of `ytSrc`

```javascript
BigPicture({
	el: e.target,
	ytSrc: 'Crzwq4CjhvA',
})
```

is equivalent to 

```javascript
BigPicture({
	el: e.target,
	iframeSrc: 'https://www.youtube.com/embed/Crzwq4CjhvA?rel=0&playsinline=1&autoplay=1',
})
```

so just add `&enablejsapi=1` or whatever else on the end and you're good to go. here's a wrapper function which should work if you want to use it:

```javascript
function BigPictureExtraParams(el, ytSrc, params) {
	BigPicture({
		el,
		iframeSrc: `https://www.youtube.com/embed/${ytSrc}?rel=0&playsinline=1&autoplay=1&${params}`,
	})
}
// invoke
BigPictureExtraParams(e.target, 'Crzwq4CjhvA', 'enablejsapi=1')
```

closing but let me know if you have any questions.
