### ISSUE TITLE
allow for playsinline for ios users

### ISSUE THREAD

**Issue by alexanderperls** [henrygd/bigpicture#5]
Very nice library, thanks! 

You might know that as part of Apple's general program to destroy the open internet, they disallowed "inline" HTML5 video playing for a long time.

They have recently opened things up a bit:

https://webkit.org/blog/6784/new-video-policies-for-ios/

So if you declare a video tag like 
`<video playsinline src = "whatever.mp4">`
Then iOS browsers will actually honor this and play the video inline, instead of full screen.

I think ideally, if possible, bigpicture should support this.

I tried modifying this line

` displayVideo.controlsList = "nodownload noremoteplayback nofullscreen playsinline";`

But for some reason it doesn't work. It might be because `controlsList` is actually only for chrome.

Any suggestions on a tweak to get bigpicture to play videos inline on iOS?

thanks!

**Comment by henrygd** [comment]
That's a good idea, thanks for the suggestion!

I don't have an iOS device to test on today, but I did update the [demo site](https://henrygd.me/bigpicture) script to include the playsinline attribute on the video element. Let me know if that works for you and I'll push to the master branch.

Otherwise I'll test Monday and update afterwards.

**Comment by henrygd** [comment]
Just updated. Adds playsinline support for html video and youtube.
