### ISSUE TITLE
Separate scripts for video demos

### ISSUE THREAD

**Issue by RakeshBootstrapUI** [henrygd/bigpicture#50]
He mate,
i love the script.
but how i add to a Html, Youtube, Vimeo video on a button click????
i trying and final result showing repeated - Error: The requested image could not be loaded.
why this message showing when i trying to get video on popup window???
i guess i miss something but didn't get the actual issue....
Please help with a little but separate code for lightbox video player?? any feedback would be great..

**Comment by henrygd** [comment]
I'd be happy to help you figure it out. Can you post a snippet of your code, or make an example on codepen or codesandbox?

**Comment by RakeshBootstrapUI** [comment]
> I'd be happy to help you figure it out. Can you post a snippet of your code, or make an example on codepen or codesandbox?

Here is link of code - https://codesandbox.io/s/bigpicturejs-demos-utx4u?file=/index.html
I tried this one with youtube-video
this running well at first view, but after i add svg icon to the button, after refresh it didn't work again and showing the same issue - Error: The requested image could not be loaded.

Actually my current project have an image gallery - (I get it work! Fine!!!)
Youtube video - Getting error
Vimeo video - Not tested
Local html video - Getting error

It would be great if you have separate demos with separate init javascript code
it would be great if it like
- Single image demo
   demo html and js code

- Image gallery demo
   demo html and js code of gallery

- local video demo
 local video html and js code belongs to only local video

- and Same for rest elements like vimeo and youtube html with separate js code..

currently only gallery and single image are separate but other iframe and videos types videos are wrapping in function like hard to understand for average Javascript user like me

Thanks for your time.
and Thanks too for awesome & cool lightbox plugin.. Keep it up..

I also love your another script side-panel like thing. really cool and lightweight, will use it also in near future..

Keep it on brother. but make it little easier to get done with demos for average users like me

**Comment by henrygd** [comment]
No problem! You can make it work by changing `e.target` to `e.currentTarget` like this:

```js
BigPicture({
  el: e.currentTarget,
  ytSrc: e.currentTarget.getAttribute("ytSrc")
});
```
After you put the svg inside the button, e.target becomes the svg when it's clicked (it's the element you clicked to trigger the event). `e.currentTarget` is always the button even when an element inside is clicked (because it's what you assigned the event listener to). It was failing because the svg does not have the `ytSrc` attribute.

Here's the working code: https://codesandbox.io/s/bigpicturejs-demos-forked-mwvtq?file=/index.html:3391-3525

I'm going to close this issue, but feel free to follow up with any question or comment.
