### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by brunnohofmann** [henrygd/bigpicture#8]
Is it possible to do a gallery with bigpicture?
THis comp is awasome, but im trying to do a lightbox gallery with an array of local images.
Can your lib do this?

**Comment by henrygd** [comment]
Unfortunately it cannot. I was working on a version that supported this, but had to drop it and haven't gotten back around to it. If I end up finishing it I'll let you know.

[baguetteBox](https://github.com/feimosi/baguetteBox.js) is a good lightweight alternative if you don't need video support.

**Comment by Albert221** [comment]
:+1:  for this feature request. Everything I need is a gallery functionality, so that when I click on one photo I can navigate to previous and next using arrows on my keyboard or arrows in UI.

And an option for limiting this gallery would be required, I think, that specifying selector of parent element would be a good approach for this.

**Comment by henrygd** [comment]
I'll try to work on this when I can. No timeline for now.

**Comment by kraigh** [comment]
@henrygd are you open to a PR for this? I'm considering using this for a project and may just add the functionality myself.

**Comment by henrygd** [comment]
@kraigh I'm always open to contributions, but in this case I'll save you the time and try to hammer it out this weekend. Meant to do it last weekend but something came up.

**Comment by henrygd** [comment]
Update: Didn't finish this weekend, but it's pretty close. Here's the [work in progress](http://bpgal.surge.sh/). Will probably hide the arrows on touch devices.

Other than that I just need to do cross browser testing and update the docs / demo site, so it'll be on here some time in the next few days. Still sitting at a svelte 3 KB gzip so I'm pretty happy with that.

**Comment by henrygd** [comment]
Gallery functionality has been added!

I'll keep this issue open for a bit so if you have any suggestions feel free to add them here.

**Comment by brunnohofmann** [comment]
Thank u soo much Henry!!!!!!!!

**Comment by Albert221** [comment]
Thank you! https://github.com/Albert221/wolszon.me/commit/30ad3b6818946c515f5d742ac0c2d70589abe658

And BTW, I personally don't like that hardcoded `[data-bp]`, because I've been using other selector myself and it would be nice to customize it. And it would be really nice if you've documented how galleries are generated in documentation, because I had to look in your source Javascript code to understand how it works.

And BTW2, next time, don't commit code changes and code style changes in the same commit, that way your whole patch (https://github.com/henrygd/bigpicture/commit/f7d370d3b974714eb7787e83ab707cf52acd9e7e) is bloated with space->tab changes and we as developers cannot see what was exactly changes.

But I'm very happy that you've successfully finished gallery feature! 🎉

**Comment by henrygd** [comment]
@brunnohofmann no problem!

@Albert221 Sorry about that!  Started using prettier recently and forget to disable it. I agree that's really annoying.

As for the attribute, I was trying to think of the easiest way to tie images to elements, to make sure the image always closes into the right place, without forcing a specific html structure. Next update (this weekend, probably) I'll let people use a custom attribute name and make the alternative array method more robust. And improve the docs :)

**Comment by kraigh** [comment]
This is awesome, thank you!

**Comment by henrygd** [comment]
I'll go ahead and close this issue now.

Small update soon to make implementation a little more flexible. If you have any ideas for other improvements, feel free to open an issue or get in touch with me another way.
